name: Can't keep up with you mind

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build this site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Build!
        shell: bash
        run: |
          pnpm fresh
          pnpm install --frozen-lockfile
          pnpm build

      - name: Sent to Cloudflare Pages
        uses: cloudflare/wrangler-action@main
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=ws-867678
