name: Can't keep up with you mind

on:
  schedule:
    - cron: "0 */12 * * *"
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build this site and fuck Hugehard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Refresh jsDelivr cache
        shell: bash
        run: |
          pnpm refresh

      - name: Build!
        shell: bash
        run: |
          pnpm install
          pnpm build
          curl -LO https://raw.githubusercontent.com/moaeiou/moaeiou/refs/heads/main/.github/workflows/format.js
          node format.js dist/index.html dist/index.html
          node format.js dist/404.html dist/404.html
          node format.js tools/moitools/index.html tools/moitools/index.html

      - name: Sent to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=ws-867678
