name: Can't keep up with you mind

on:
  push:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    name: Build this site and fuck Hugehard
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up pnpm
        uses: pnpm/action-setup@master

      - name: Set up Node.js
        uses: actions/setup-node@main
        with:
          node-version: latest

      - name: Build!
        shell: bash
        run: |
          pnpm install
          pnpm build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name=867678-xyz
